### ISSUE TITLE
Duplicate Bookmarks on same Frequency after imports

### ISSUE THREAD

**Issue by yah00078** [jketterl/openwebrx#320]
Hello,
First of all, thank you for all work you've done !

Using multiples PC, I regularly import locals Bookmarks to server. 

I found that every import re-add already saved frequencies, generating many duplicates entries. 

Can change the behavior ? 

Thank you !

**Comment by jketterl** [comment]
Please use the issue template for feature requests.

The definition of a "duplicate" is a bit of an issue here. Checking for the frequency alone seems insufficient since frequency sharing is a thing, checking for the name in addition would mean that any edit to the name would make the problem re-appear.

I'd say the recommendation would be to delete any local bookmarks once the import has been successful, however there's the problem that the local bookmarks are currently hidden behind the server side ones. Maybe this could be an option in the import dialogue.

Another possible solution would be to only check the stations you'd actually like to import in the import dialogue.

**Comment by yah00078** [comment]
Ok thank you
