### ISSUE TITLE
Feature request: switch from GoogleMaps to OpenStreetMap

### ISSUE THREAD

**Issue by fouine95** [jketterl/openwebrx#346]
**Feature description**
replace /map feature from Googlemaps to OpenStreetMaps

**Target audience**
Any OWRX user who is concerned about privacy and the use of GAFAM services

**Comment by jketterl** [comment]
This has been requested before (see #238).

Notes:

- This is not a feature request. The current map works and provides all the functionality, switching to OSM will not provide any new functionality.
- Google Maps still offers superior quality and user experience. There is not reason to switch to OSM from a technical standpoint.
- Since whatever map you would like to use is more of a personal preference, there will be no switch. If anything, there would be an option to switch between map providers.
- I have no intention of maintaining two implementations of the map. If you feel like you would like to contribute and maintain an OSM implementation, please let me know.
- There has already been an implementation of OSM in OpenWebRX at some point in the past. It was removed because it failed (due to external factors) and nobody was available to repair it.
