### ISSUE TITLE
Layout problems in the profile settings screen

### ISSUE THREAD

**Issue by luarvique** [jketterl/openwebrx#351]
**Describe the bug**
When a profile option (in source/__init__.py) has a long infotext field, the resulting option description does not wrap in the browser window. Instead, it extends the input field beyond the visual container.

**To Reproduce**
Select an arbitrary profile in the Settings and add the "Oscillator offset" (lfo_offset) option to it. Try resizing the browser window.

**Expected behavior**
The oscillator offset option description wraps as the window becomes narrower.

**Installation method**
From packages

**Versions**
1.2.1 has it

**Log messages**
Nope

**Additional context**
Tested on the latest Firefox and Chrome.

**Comment by jketterl** [comment]
I've had a look. Seems like the problem here is that there's an implicit minimum width on `<input>` elements that is not immediately obvious.

I have changed the flex settings on the parent container to a `flex-basis: 0` in https://github.com/jketterl/openwebrx/commit/6026aaedbae23ec025da3043ebfd188b4ea071b4 in order to tell the browser to ignore the width now, and it looks like the overflow is no longer happening.

**Comment by luarvique** [comment]
Indeed, it has fixed things! Thanks!
