### ISSUE TITLE
Documentation update - changing USB bus/device numbers in Docker containers *can* be detected

### ISSUE THREAD

**Issue by kx1t** [jketterl/openwebrx#364]
**Describe the bug**
Documentation update request

**To Reproduce**
n/a

**Expected behavior**
n/a

**Installation method**
Docker image

**Versions**
all/any

**Log messages**
n/a

**Additional context**

In the [SDRPlay for Docker documentation](https://github.com/jketterl/openwebrx/wiki/SDRPlay-device-notes#using-sdrplay-devices-in-docker-containers), you wrote:

>The docker device forwarding unfortunately does not handle newly added USB devices once the container has been started. This means that the USB re-registration only shows up as a device removal from the perspective of the docker container. The new device that is created during the re-registration never becomes visible inside the docker container.

In fact, there is a way around this by using `device_cgroup_rules` and mapping `/dev` to a volume. See the docker-compose example below.

So here, instead of mapping the USB port via the `device:` directive, we figured out that on all hardware we checked (Raspi 3B+/4B, LePotato, OrangePi, x86 laptop, etc.) and all Debian variations we had available (RaspiOS Stretch/Buster/Bullseye/Bookworm, DietPi Bullseye/Bookworm, Ubuntu from 20.10 onwards, etc.), all USB devices are in cgroup 189. We are adding access for the container to this specific cgroup with the `device_cgroup_rules` directive, and then we map `/dev` directly into the container so these devices become accessible on `/dev`.

Now, when the Bus and/or Device number change, the new bus/device are available within the container for the software to deal with. This is in contrast to a setup that uses the `device` directive, where the bus/device numbers are only read on container start, as you already noted in the current documentation.

```yaml
version: '3.8'

services:
  openwebrx:
    image: jketterl/openwebrx-full:stable
    container_name: openwebrx
    hostname: openwebrx
    device_cgroup_rules:
      - 'c 189:* rwm'
    restart: always
    tmpfs:
      - /tmp/openwebrx
    volumes:
      - /opt/openwebrx/data:/var/lib/openwebrx
      - /opt/openwebrx/config:/etc/openwebrx
      - /dev:/dev:rwm
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 8073:8073

**Comment by jketterl** [comment]
OK so I've been brooding over this for a bit.

The base problem here is that... I don't think this should be on the OpenWebRX documentation because it's docker knowledge. So as far as I'm concerned, this should be somewhere on the docker documentation. That way the wiki could simply link there.

In general, I'm trying not to turn the project documentation into a docker knowledge base. Docker is a complicated system and there's a lot of things you'll need to know and understand in order to run applications in its containers, but that doesn't mean that all of these things need to be available on the OpenWebRX documentation.

Also... I'd say that the statement given on the wiki page is basically still true: What your workaround does is it basically handles the device additions itself, not using the intended `device` mechanism provided by docker. So, in the end, the limitation of docker still persists.

In the end, it would help everybody if docker would work on this problem, but I have no idea if this will happen.
