### ISSUE TITLE
CAT control 

### ISSUE THREAD

**Issue by oh3gai** [jketterl/openwebrx#382]
Hi!

First of all, thanks from awesome work. This is killer app for radio enthusiastic.

I would like to see CAT control feature where transmitter acts as slave to openwebrx for example via hamlib.

transmitter side runs rigctld which enables tcp link to radio CAT port 
rigctld -m 1022 -r /dev/ttyUSB0 -s 4800 -t 4532  

OWRX side could be something like this where frequency and mode varies with OWRX freq -
rigctl -m 2 -r localhost:4532 F 7253500 M LSB 0 
or
echo 'F 7253500 M LSB 0' | nc -w1 localhost 4532

This would allow to have transmitter which change frequency and mode in sync with openwebrx. This feature would act as radio panadapter.

Thanks again for the great work.

Br, Jarno OH3GAI

**Comment by jketterl** [comment]
Please use the issue template.

Sorry, but this kind of feature is not possible. It is not possible to execute client applications from the browser. Besides, it would open up a whole slew of other considerations, e.g. the reliance of certain binaries being installed on the client. In addition, there's also the problem of getting into all kind of problems due to differences in platform. So no, certainly not this way.

Also, in general, please have a look at the intended mode of operation of OpenWebRX. It is not expected that an OpenWebRX receiver is part of the same station as the client transmitter, as such the operation of a "panadapter" doesn't really apply.

**Comment by oh3gai** [comment]
Hi!

No problem, thanks for the fast reply. 

Actually I know that there is this app "CATsync" which does the job, but as far as I know it's limited to windows and I try to avoid that.

Anyways, OWRX is great peace of work. Thanks!

Br, Jarno
