### ISSUE TITLE
Change timezone via variable or web UI

### ISSUE THREAD

**Issue by juantecnico** [jketterl/openwebrx#386]
Im trying to change the timezone to adjust to my locatión, but cant see the way.
Would be nice to be able to change TZ via web UI or docker ENV.

**Comment by jketterl** [comment]
Please use the issue template.

OpenWebRX is timezone-agnostic on purpose since it is expected that users come from around the globe. As such, configuring your instance to your local timezone does not make a lot of sense.

The universal standard for such applications is UTC, and most people affiliated with radio will know how to convert between that and their local time.

**Comment by jketterl** [comment]
nothing heard, closing.
