### ISSUE TITLE
HTTPS mentioned instead of HTTP

### ISSUE THREAD

**Issue by ofadam** [jketterl/openwebrx#39]
On the Raspberry Pi image instructions in the readme, it mentions https://openwebrx:8073/  – I believe that should just be http://.

**Comment by jketterl** [comment]
actually, it should be https, but without the port. fixed :)

the raspberry image comes complete with an nginx that listens on https (self-signed only though), the reason behind is that the newer "AudioWorkletNode" audio playback requires https. I haven't advertised this much since it isn't widely supported, nor does it work properly. It is the new upcoming standard though...
