### ISSUE TITLE
RPi Image: configure wlan0 as fallback if eth0 goes down

### ISSUE THREAD

**Issue by chjohn22** [jketterl/openwebrx#58]
Hello

I am using your newest RPi image from 20.02.2020 on a RPi 4, and I am very happy with it.
It would be useful, if the stock network configs could be set up in a way, that if there is no connection over eth0, raspbian would automatically connect via wlan0 with the credentials located in a wpa_supplicants.conf file in the boot folder.
When I try to boot first with a wpa_supplicants.conf file already in place, the RPi does connect to the Wifi, but openwebrx can't be accessed in the web browser and ssh does not work too.

Wifi connectivity can be very useful on field days, where you could create a small wifi network on a battery powered travel router or to increase flexibility in shacks without ethernet.

**Comment by jketterl** [comment]
The network configuration is pretty much stock Raspbian, and I don't intend to mess with it.

The Wifi issue has been discussed before on the pi-gen repository: https://github.com/RPi-Distro/pi-gen/issues/385

Basically, this is a limitation that is down to the fact that nobody can predict in what country an image is going to be used, and as such there's no way to configure the Wifi in accordance with the local regulations.

I know that the last Raspbian has pretty much blocked any automated deployment of Wifi configurations, not sure if this is their final move. All I know is that I don't want to exclude anybody from using the image just because the Wifi is set up incorrectly for their location. I will of course keep this updated with changes from Raspbian, so if they figure something out it'll be in the next OpenWebRX images, too.

You can of course fork the build chain and perform your modifications for your local use: https://github.com/jketterl/openwebrx-pi-gen
