### ISSUE TITLE
Squelch doesn't work in DIGI Packet

### ISSUE THREAD

**Issue by kolbma** [jketterl/openwebrx#65]
At least in DIGI **Packet** mode the squelch setting doesn't do anything.
Maybe the reason is that the SQU is not fast enough for digi mode.
But then a feature for "audio output squelch" would be fine, to simply mute the noise below db level.

**Comment by jketterl** [comment]
That is pretty much intended. The digital decoders don't mind the noise, the squelch can only have negative effects in that case.

Unfortunately, the way things are setup, I cannot have a separate squelch on the audio since that would mean I'd have to run a second demodulator, which I'm not going to do as the additional CPU usage is unacceptable.

This also affects Pocsag.

**Comment by kolbma** [comment]
Ok. Then what do you think about disabling the squelch control in these modes?

**Comment by jketterl** [comment]
definitely the way to go, but need to have a look if it's realistic with the current codebase (it's a lot of spaghetti code). i may need to rewrite some more stuff first.

**Comment by jketterl** [comment]
looks like I only referenced this in the commits, but didn't post an update. There's been a rework of a lot of the frontend code, and I included the suggestion in that move, so the squelch control is now disabled on the modes that don't support it.
