### ISSUE TITLE
Info ONLY: Workarounds for openwebrx CPU Load Reduce + Hanging IO

### ISSUE THREAD

**Issue by linuxonlinehelp** [jketterl/openwebrx#67]
[https://github.com/linuxonlinehelp/openwebrx-workarounds-bugfixes/wiki/Openwebrx-Help-Workarounds](url)

hope its useful..

**Comment by D0han** [comment]
This link is not correct, can you fix markdown for it?

**Comment by jketterl** [comment]
Even with the correct link, it's not very helpful since most of the instructions on that page are based on the "original" version and are no longer relevant.

- Passing the Squelch as a URL fragment is no longer supported. Instead, you can set the `initial_squelch_level` on the config profiles.
- The startup delay of the FFT functions has been fixed and is no longer an issue when you're using my fork of csdr (I also sent the change upstream, however there's no attention whatsoever... here's the pull request: https://github.com/ha7ilm/csdr/pull/51)
- there's no index.wrx any more.

Please stop bringing in outdated information, it is only confusing for users.

**Comment by linuxonlinehelp** [comment]
i purged it! iam out, (the old developer is a friend of me)
