### ISSUE TITLE
ALSA or alternate IQ input? (feature)

### ISSUE THREAD

**Issue by azwirko** [jketterl/openwebrx#87]
Hi
  I am running a Red Pitaya emulating an HPSDR 

http://pavel-demin.github.io/red-pitaya-notes/sdr-receiver-hpsdr/

  I also am running that along with using CWSL_Tee on Windows

https://github.com/HrochL/CWSL

  to break out the IQ stream and feed it to multiple apps like CW Skimmer and RTTY Skimmer.  I see there is an associated connector for CWSL_Tee called CWSL_WebSDR 

https://www.dl1glh.de/cwsl_websdr.html

  that produces an IQ stream usable by the WebSDR software which can read IQ data from an ALSA device.  I was wondering if there is an ALSA input device in OpenWebRX that might also consume this data stream? OR What might be the easiest way to re-use this IQ data.  

  CWSL_Tee also has a CWSL_Net connector that feeds IQ data to the ghpsdr3 project

http://napan.ca/ghpsdr3/index.php/Main_Page

  So I wonder if this may be another path to get data into OpenWebRX?

  If none of the existing mechanisms could be reused, I'd like to write a connector for CWSL_Tee that could feed into OpenWebRX and I'm looking for any info on what would be the easiest path to pursue. 

Thanks for any info and direction you can provide.

73

andyz - K1RA

**Comment by jketterl** [comment]
Hello Andy,

I'm not sure how to approach the Red Pitaya since I don't own one, nor do I have much experience with it.

There's a soapy module for the Red Pitaya available, but I'm in doubt it will fit your specific needs: https://github.com/pothosware/SoapyRedPitaya/wiki

There has been some work to read IQ data over alsa to support the FiFi SDR, you could have a look at how that is implemented. There will probably an issue with device control, since sound cards don't have any HF specific parameters. In order to make up a valid source for this version of OpenWebRX, some kind of control channel needs to be available.
